services:
  emulatorjs:
    image: node:alpine
    container_name: emulatorjs
    working_dir: /app
    command: node server.js
    ports:
      - 80:80
    volumes:
      - ./server.js:/app/server.js:ro
      - ./web:/app/web:ro
      - ./roms:/app/roms
    restart: unless-stopped